# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
        config.vm.define :servidorPXE do |servidorPXE|
                servidorPXE.vm.box = "bento/centos-7.8"
                servidorPXE.vm.network :private_network, ip: "192.168.50.22"
                servidorPXE.vm.hostname = "servidorPXE"
        end
end